"""updated length-text email

Revision ID: 756c552798a9
Revises: e07028bcfe70
Create Date: 2025-02-05 11:01:39.368052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756c552798a9'
down_revision = 'e07028bcfe70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avatars', 'email',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('avatars', 'email',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    # ### end Alembic commands ###
